In [2]:
import numpy as np

In [3]:
w_a = np.load("../raw_data/projections/projected_w_a.npz")["w"]
w_b = np.load("../raw_data/projections/projected_w_a.npz")["w"]


In [4]:
w_a

array([[[ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
          0.24151102, -0.01633999],
        [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
          0.24151102, -0.01633999],
        [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
          0.24151102, -0.01633999],
        ...,
        [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
          0.24151102, -0.01633999],
        [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
          0.24151102, -0.01633999],
        [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
          0.24151102, -0.01633999]]], dtype=float32)

In [5]:
w_a.shape

(1, 16, 512)

In [7]:
import scipy.interpolate

# Define the "time" points for w_a and w_b
x = np.array([0, 1])

# Stack w_a and w_b along the first dimension
y = np.stack([w_a, w_b], axis=0)

# Create the interpolation function
interp = scipy.interpolate.interp1d(x, y, kind='linear', axis=0)

# Define the time points at which you want to interpolate
num_interps = 10
x_interp = np.linspace(0, 1, num_interps)
display('x_interp', x_interp)

# Generate the interpolated w vectors
w_interp = interp(x_interp)
display('w_interp', w_interp)

'x_interp'

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

'w_interp'

array([[[[ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         ...,
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999]]],


       [[[ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         [ 0.4201065 ,  0.50840396, -0.19554576, ...,  0.36482847,
           0.24151102, -0.01633999],
         ...,
         [ 0.4201065 ,  0.508403